language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cqng' ]; then cd .. && eval "mv $currentfolder generator-cqng" && cd generator-cqng; fi

